language: ruby

rvm:
  - 2.3.3

env:
  - RAILS_ENV=test

addons:
  postgresql: '9.4'

install:
  - bundle install
  - cd client
  - node -v
  # update npm
  - npm install npm -g

before_script:
  - cp config/database.yml.travis config/database.yml

script:
 - bundle exec rubocop
 - bundle exec rake db:schema:load
 - bundle exec rspec
 - cd client && npm test
