language: ruby
rvm:
 - 2.3.3

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database address_book_pwc_test;' -U postgres

script:
 - bundle exec rubocop
 - bundle exec rspec spec